#!/usr/bin/env node

/* ═══════════════════════════════════════════════════════════════
   MEMORY-INDEX — auto-generate .claude/memory/INDEX.md

   Scans all memory entries, parses YAML frontmatter, produces a
   structured sommaire by type with tag counts and status highlights.

   Usage:
     pnpm memory:index           → regenerate INDEX.md
     node scripts/memory-index.js
   ═══════════════════════════════════════════════════════════════ */

import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';

import { PATHS } from './utils/paths.js';

const CHECK_MODE = process.argv.includes('--check');

// WHY: STEAKSOAP_TEST_ROOT env var lets smoke tests point the script at a
// temp-dir fixture instead of the real repo root. Production runs don't
// set it and fall through to PATHS.root unchanged.
const ROOT = process.env.STEAKSOAP_TEST_ROOT || PATHS.root;
const MEMORY_DIR = join(ROOT, '.claude/memory');
const INDEX_PATH = join(MEMORY_DIR, 'INDEX.md');
const MEMORY_PATH = join(MEMORY_DIR, 'MEMORY.md');
const TAGS_PATH = join(MEMORY_DIR, 'TAGS.md');
const TYPES = ['decisions', 'feedback', 'patterns', 'frictions', 'sessions'];
const REQUIRED_FIELDS = ['id', 'date', 'type', 'tags', 'scope', 'status'];

// WHY: release entries are auto-generated by scripts/memory-record-release.js
// at every version cut. They accumulate fast (1 per release) and bury the real
// decision content in the INDEX. We detect them via filename pattern and
// segregate them in a collapsible "Release log" section — they remain
// indexed for traceability, just visually out of the way.
const isRelease = (entry) =>
  /release-v\d+\.\d+\.\d+\.md$/.test(entry.path) || (entry.id || '').startsWith('release-v');

const errors = [];
const recordError = (file, reason) =>
  errors.push(`${relative(ROOT, file).replace(/\\/g, '/')}: ${reason}`);

// Parse canonical tag vocabulary from TAGS.md
function loadCanonicalTags() {
  const content = readFileSync(TAGS_PATH, 'utf-8');
  const matches = content.match(/`#[a-z0-9-]+`/g) || [];
  return new Set(matches.map((t) => t.replace(/`/g, '')));
}

// Simple YAML frontmatter parser (handles our fixed schema)
function parseFrontmatter(md) {
  const match = md.match(/^---\n([\s\S]*?)\n---/);
  if (!match) return null;
  const fm = {};
  for (const line of match[1].split('\n')) {
    const kv = line.match(/^(\w+):\s*(.*)$/);
    if (!kv) continue;
    const [, key, raw] = kv;
    if (raw.startsWith('[')) {
      fm[key] = raw
        .slice(1, -1)
        .split(',')
        .map((s) => s.trim())
        .filter(Boolean);
    } else {
      fm[key] = raw.trim();
    }
  }
  return fm;
}

function walk(dir) {
  const entries = [];
  let items;
  try {
    items = readdirSync(dir);
  } catch {
    return entries;
  }
  for (const name of items) {
    if (name.startsWith('.')) continue;
    const full = join(dir, name);
    if (statSync(full).isDirectory()) continue;
    if (!name.endsWith('.md')) continue;
    const raw = readFileSync(full, 'utf-8');
    const fm = parseFrontmatter(raw);
    if (!fm) {
      recordError(full, 'missing or malformed YAML frontmatter (expected leading `---` block)');
      continue;
    }
    const missing = REQUIRED_FIELDS.filter((f) => fm[f] === undefined || fm[f] === '');
    if (missing.length > 0) {
      recordError(full, `missing required frontmatter fields: ${missing.join(', ')}`);
      continue;
    }
    const titleMatch = raw.slice(raw.indexOf('---', 3) + 3).match(/^\s*#\s+(.+)$/m);
    entries.push({
      path: relative(MEMORY_DIR, full).replace(/\\/g, '/'),
      title: titleMatch ? titleMatch[1].trim() : name.replace('.md', ''),
      ...fm,
    });
  }
  return entries;
}

function main() {
  const canonical = loadCanonicalTags();
  const all = [];
  const unknownTags = new Map();

  for (const folder of TYPES) {
    const typeDir = join(MEMORY_DIR, folder);
    const entries = walk(typeDir);
    // WHY: sort by date DESC, then by filename DESC for tie-break. Sessions
    // use YYYY-MM-DD-HHMM.md so same-day entries need HHMM ordering to show
    // truly latest. Previous sort-by-date-only surfaced 00:15/01:15/02:30 as
    // "recent" when real latest were 14:15/15:00/15:10 (cross-audit flagged it).
    entries.sort((a, b) => {
      const byDate = (b.date || '').localeCompare(a.date || '');
      if (byDate !== 0) return byDate;
      return (b.path || '').localeCompare(a.path || '');
    });
    for (const e of entries) {
      all.push({ ...e, folder });
      for (const tag of e.tags || []) {
        if (!canonical.has(tag)) {
          unknownTags.set(tag, (unknownTags.get(tag) || 0) + 1);
        }
      }
    }
  }

  // Tag counts across all entries
  const tagCount = {};
  for (const e of all) {
    for (const tag of e.tags || []) {
      tagCount[tag] = (tagCount[tag] || 0) + 1;
    }
  }
  const sortedTags = Object.entries(tagCount).sort((a, b) => b[1] - a[1]);

  const now = new Date().toISOString().slice(0, 10);
  const lines = [];
  lines.push('# Memory Index');
  lines.push('');
  lines.push(`> Auto-generated by \`pnpm memory:index\` on ${now}. Do not edit by hand.`);
  lines.push('');
  lines.push(`**${all.length}** entries · **${sortedTags.length}** distinct tags`);
  lines.push('');

  if (unknownTags.size > 0) {
    lines.push('## ⚠ Unknown tags detected');
    lines.push('');
    lines.push('The following tags are not in `TAGS.md` canonical vocabulary:');
    lines.push('');
    for (const [tag, count] of unknownTags) {
      lines.push(`- \`${tag}\` (${count} occurrences)`);
    }
    lines.push('');
    lines.push('Either fix the entry or add the tag to `TAGS.md` via a decision.');
    lines.push('');
  }

  for (const folder of TYPES) {
    const entries = all.filter((e) => e.folder === folder);
    if (entries.length === 0) continue;
    lines.push(`## ${folder.charAt(0).toUpperCase() + folder.slice(1)}`);
    lines.push('');
    // WHY: split releases out of the "real decisions" pool — they are traceable
    // archive entries, not load-bearing context. Frontmatter still greppable.
    const releases = entries.filter(isRelease);
    const nonRelease = entries.filter((e) => !isRelease(e));
    const active = nonRelease.filter((e) => e.status !== 'deprecated' && e.status !== 'superseded');
    const archived = nonRelease.filter((e) => e.status === 'deprecated' || e.status === 'superseded');
    for (const e of active) {
      const tags = (e.tags || []).join(' ');
      lines.push(`- **${e.date || '—'}** — [${e.title}](${e.path}) · ${tags}`);
    }
    if (archived.length > 0) {
      lines.push('');
      lines.push('<details><summary>Archived</summary>');
      lines.push('');
      for (const e of archived) {
        const tags = (e.tags || []).join(' ');
        lines.push(`- ~~**${e.date || '—'}** — [${e.title}](${e.path}) · ${e.status} · ${tags}~~`);
      }
      lines.push('');
      lines.push('</details>');
    }
    if (releases.length > 0) {
      lines.push('');
      lines.push(`<details><summary>Release log (${releases.length})</summary>`);
      lines.push('');
      for (const e of releases) {
        lines.push(`- **${e.date || '—'}** — [${e.title}](${e.path})`);
      }
      lines.push('');
      lines.push('</details>');
    }
    lines.push('');
  }

  lines.push('## Tag frequency');
  lines.push('');
  lines.push('| Tag | Count |');
  lines.push('|---|---|');
  for (const [tag, count] of sortedTags) {
    lines.push(`| \`${tag}\` | ${count} |`);
  }
  lines.push('');

  const next = lines.join('\n') + '\n';

  // ─── MEMORY.md live digest ────────────────────────────────
  // WHY: the full INDEX gets heavy fast (release logs, archived entries,
  // tag frequency table). MEMORY.md is the ~2 KB snapshot the SessionStart
  // hook loads at the top of every session — recent sessions + active
  // decisions + open frictions. The hook falls back to INDEX.md if MEMORY
  // is missing, so the two coexist.
  const digestLines = [];
  digestLines.push('# Memory Digest');
  digestLines.push('');
  digestLines.push(`> Auto-generated by \`pnpm memory:index\` on ${now}. Live snapshot loaded at session start.`);
  digestLines.push('> For the full catalogue, see [`INDEX.md`](INDEX.md).');
  digestLines.push('');

  const recentSessions = all
    .filter((e) => e.folder === 'sessions')
    .slice(0, 3);
  if (recentSessions.length > 0) {
    digestLines.push('## Recent sessions (top 3)');
    digestLines.push('');
    for (const e of recentSessions) {
      digestLines.push(`- **${e.date}** — [${e.title}](${e.path})`);
    }
    digestLines.push('');
  }

  const activeDecisions = all
    .filter((e) => e.folder === 'decisions')
    .filter((e) => !isRelease(e))
    .filter((e) => e.status === 'active')
    .slice(0, 5);
  if (activeDecisions.length > 0) {
    digestLines.push('## Active decisions (top 5)');
    digestLines.push('');
    for (const e of activeDecisions) {
      const tags = (e.tags || []).slice(0, 4).join(' ');
      digestLines.push(`- **${e.date}** — [${e.title}](${e.path}) · ${tags}`);
    }
    digestLines.push('');
  }

  const openFrictions = all
    .filter((e) => e.folder === 'frictions')
    .filter((e) => e.status === 'active');
  if (openFrictions.length > 0) {
    digestLines.push('## Open frictions');
    digestLines.push('');
    for (const e of openFrictions) {
      digestLines.push(`- **${e.date}** — [${e.title}](${e.path})`);
    }
    digestLines.push('');
  }

  const activePatterns = all
    .filter((e) => e.folder === 'patterns')
    .filter((e) => e.status === 'active');
  if (activePatterns.length > 0) {
    digestLines.push('## Active patterns');
    digestLines.push('');
    for (const e of activePatterns) {
      digestLines.push(`- **${e.date}** — [${e.title}](${e.path})`);
    }
    digestLines.push('');
  }

  digestLines.push('## Deep dive');
  digestLines.push('');
  digestLines.push(`- Full catalogue (${all.length} entries): [\`INDEX.md\`](INDEX.md)`);
  digestLines.push('- Canonical tag vocabulary: [`TAGS.md`](TAGS.md)');
  digestLines.push('- Grep by domain: `grep -rl "#<tag>" .claude/memory/`');
  digestLines.push('');
  const digest = digestLines.join('\n') + '\n';

  // ─── Write / check both files ────────────────────────────
  const diffAny = (path, content) => {
    const current = existsSync(path) ? readFileSync(path, 'utf-8') : '';
    return current !== content;
  };

  if (CHECK_MODE) {
    const indexDrift = diffAny(INDEX_PATH, next);
    const memoryDrift = diffAny(MEMORY_PATH, digest);
    if (indexDrift || memoryDrift) {
      const names = [];
      if (indexDrift) names.push(relative(ROOT, INDEX_PATH));
      if (memoryDrift) names.push(relative(ROOT, MEMORY_PATH));
      console.error(`\n  ✗ Memory digest out of date: ${names.join(', ')}. Run \`pnpm memory:index\`.`);
      process.exit(1);
    }
    console.log(`  ✓ INDEX.md + MEMORY.md up to date (${all.length} entries)`);
  } else {
    writeFileSync(INDEX_PATH, next);
    writeFileSync(MEMORY_PATH, digest);
    console.log(`  ✓ Wrote ${relative(ROOT, INDEX_PATH)} (${all.length} entries)`);
    console.log(`  ✓ Wrote ${relative(ROOT, MEMORY_PATH)} digest (${recentSessions.length} recent sessions, ${activeDecisions.length} active decisions, ${openFrictions.length} open frictions)`);
  }

  // WHY: closed-set tag vocabulary is a protocol invariant — fail hard rather
  // than warn, so unknown tags surface in CI before they accumulate.
  if (unknownTags.size > 0) {
    console.error(`\n  ✗ ${unknownTags.size} unknown tag(s) — not in .claude/memory/TAGS.md:`);
    for (const [tag, count] of unknownTags) console.error(`    - ${tag} (${count} occurrence${count === 1 ? '' : 's'})`);
    console.error('\n  Either fix the entries or add the tag to TAGS.md via a decision entry.\n');
    process.exit(1);
  }

  if (errors.length > 0) {
    console.error(`\n  ✗ ${errors.length} malformed memory entr${errors.length === 1 ? 'y' : 'ies'}:`);
    for (const e of errors) console.error(`    - ${e}`);
    console.error('\n  Fix each file per .claude/rules/memory-protocol.md (required frontmatter).\n');
    process.exit(1);
  }
}

main();
